### ISSUE TITLE
stickersProvider/pending_tasks?QUERY_LIMIT=1' is not supported by this ContentProvider

### ISSUE THREAD

**Issue by mslobodan** [908Inc/stickerfactory#2]
I am getting this error:

```
E/DatabaseUtils: Writing exception to parcel
    java.lang.IllegalArgumentException: The uri 'content://com.myapp.myapp_stage.stickersProvider/pending_tasks?QUERY_LIMIT=1' is not supported by this ContentProvider
        at vc908.stickerfactory.provider.StickersProvider.getQueryParams(StickersProvider.java:207)
        at vc908.stickerfactory.provider.base.BaseContentProvider.query(BaseContentProvider.java:130)
        at vc908.stickerfactory.provider.StickersProvider.query(StickersProvider.java:149)
        at android.content.ContentProvider.query(ContentProvider.java:1020)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
        at android.os.Binder.execTransact(Binder.java:565)
07-25 22:18:48.948 29916-29928/? E/DatabaseUtils: Writing exception to parcel
    java.lang.IllegalArgumentException: The uri 'content://com.myapp.myapp_stage.stickersProvider/stickers' is not supported by this ContentProvider
        at vc908.stickerfactory.provider.StickersProvider.getQueryParams(StickersProvider.java:207)
        at vc908.stickerfactory.provider.base.BaseContentProvider.query(BaseContentProvider.java:130)
        at vc908.stickerfactory.provider.StickersProvider.query(StickersProvider.java:149)
        at android.content.ContentProvider.query(ContentProvider.java:1020)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
        at android.os.Binder.execTransact(Binder.java:565)
```

I have added stickers module to my app, and this error is shown sometimes. `App has stopped` dialog is shown and when I click on close app dialog is closed and app works normally.

This is not happening always. Just sometimes.
Does anyone know what could be issue?

**Comment by dehimb** [comment]
hi, @mslobodan 
We will try to find a solution for this unexpected behavior.

**Comment by mslobodan** [comment]
@dehimb Have you been able to reproduce it?

**Comment by dehimb** [comment]
@mslobodan currently no
